# mysql配置
attend:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: 10.10.107.190
    port: 3306
    database: springboot_demo
# 配置自己的本机数据库用户名和密码
    username: root
    password: Maker2024
#  redis:
#    host: 10.15.107.211
#    port: 6379
#    password: 123456
#    database: 10
# 配置自己的阿里云OSS
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tDGrULGdBBeUK9nAvSm
    access-key-secret: su3JIAi83LdgyhuqwGcsmJ76KXGzzN
    bucket-name: sky-itcast-shuo
  wechat:
#    appid: wx3f400a89aa622c96
#    secret: f778d7d79435b543ebf8fb93a7271bdf
    appid: wx216cea77f09f5269
    secret: 67f610277704aea4209fe001fbfb9f19